use api route

diff --git a/.github/workflows/on-push.yml b/.github/workflows/on-push.yml
--- a/.github/workflows/on-push.yml
+++ b/.github/workflows/on-push.yml
@@ -22,6 +22,18 @@ jobs:
         run: |
           docker build -t bouzomgi/micro-server:latest .
 
+      - name: Run and check Docker container health
+        run: |
+          docker run -d --name test-container -p 80:80 bouzomgi/micro-server:latest
+          sleep 10  # Allow some time for the container to start and perform the health check
+          health_status=$(docker inspect --format='{{.State.Health.Status}}' test-container)
+          if [ "$health_status" != "healthy" ]; then
+            echo "Health check failed. Status: $health_status"
+            exit 1
+          else
+            echo "Health check passed."
+          fi
+
       - name: Push Docker image
         run: |
           docker push bouzomgi/micro-server:latest
